name: preview

on:
  pull_request:
    branches:
      - master
      - dev
      - release-v*
  push:
    branches:
      - master
      - dev
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v2

      - name: Use node v14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install vercel
        run: npm install -g vercel

      - name: Deploy preview
        id: deploy
        if: ${{ github.ref != 'refs/heads/master' }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN --confirm --no-clipboard)
          echo "::set-output name=deployment_url::$DEPLOYMENT_URL"
      - name: Teardown the deployment
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            This pull request is deployed automatically with Vercel.
            ## landing-page-gdsc-uit
            💪 Preview: [${{ steps.deploy.outputs.DEPLOYMENT_URL }}](${{ steps.deploy.outputs.DEPLOYMENT_URL }})
          check_for_duplicate_msg: true